name: Elixir CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-elixir@885971a72ed1f9240973bd92ab57af8c1aa68f24
      with:
        elixir-version: '1.11.4' # Define the elixir version [required]
        otp-version: '23.3' # Define the OTP version [required]
    
    - name: Restore libsodium        
      uses: actions/cache@v2.1.4
      with:
        path: ~/libsodium
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
        
    - name: Install libsodium
      run: |          
        mkdir -p ~/libsodium - 
        cd ~/libsodium 
        curl -L https://download.libsodium.org/libsodium/releases/LATEST.tar.gz -o libsodium.tar.gz 
        tar xfvz libsodium.tar.gz 
        ls . 
        cd ~/libsodium/libsodium-stable/ 
        ./configure --prefix=/usr
        make 
        make check 
        sudo make install 
        sudo mv src/libsodium /usr/local/ 
        sudo ldconfig
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test
    - name: Compile warnings as error
      run: mix compile --warnings-as-errors --force
    - name: Run credo
      run: mix credo --strict
    - name: Check code format
      run: mix format --check-formatted
